### ISSUE TITLE
"RestKit/RestKit.h" file not found

### ISSUE THREAD

**Issue by dogvscat** [RestKit/RestKit#2341] opened 2015-10-30 08:41 UTC
Xcode7.1  CocoaPods: 0.39.0
1. if i use `Installing RestKit v0.20.x as a Git Submodule`,when i archive,it shows the error"RestKit/RestKit.h file not found" in AppDelegate, but i can run it on my device;

2. I konw above method is not  recommended now, so i use CocoaPods, and RestKit version is 0.25.0, when i pod install it ,i still get errors "RestKit/RestKit.h" file not found.

So any help?

**Comment by segiddins** [comment] 2015-10-30 12:52
This is a duplicate of a known issues. There's an open PR with a fix that will be merged soon.

**Closed by segiddins** 2015-10-30 12:52 UTC

**Comment by kwabford** [comment] 2015-11-03 19:40
@dogvscat This was the only thing that I could get to work. https://forums.developer.apple.com/message/79355#79355

**Comment by dogvscat** [comment] 2015-11-05 03:20
@kwabford  you really saved my life.Thx a lot .
