### ISSUE TITLE
Xcode 8 error log

### ISSUE THREAD

**Issue by uchiaTziki** [RestKit/RestKit#2451] opened 2016-08-07 13:27 UTC
When saving on the new Xcode 8 I'm getting this error log: 
`[error] error: An observer of NSManagedObjectContextDidSaveNotification illegally threw an exception.  Objects saved = {
    inserted = "{(\n)}";
    managedObjectContext = "<_PFWeakReference: 0x600000428220>";
    updated = "{(\n)}";
} and exception = [<_PFWeakReference 0x600000428220> valueForUndefinedKey:]: this class is not key value coding-compliant for the key @count. with userInfo = {
    NSTargetObjectUserInfoKey = "<_PFWeakReference: 0x600000428220>";
    NSUnknownUserInfoKey = "@count";
}`

Any idea if it has to do with this class: RKManagedObjectStore.m with the function:
`static NSSet *RKSetOfManagedObjectIDsFromManagedObjectContextDidSaveNotification(NSNotification *notification)
{
    NSUInteger count = [[[notification.userInfo allValues] valueForKeyPath:@"@sum.@count"] unsignedIntegerValue];
    NSMutableSet *objectIDs = [NSMutableSet setWithCapacity:count];
    for (NSSet *objects in [notification.userInfo allValues]) {
        [objectIDs unionSet:[objects valueForKey:@"objectID"]];
    }
    return objectIDs;
}`

Thanks

**Comment by icy1007** [comment] 2016-08-09 00:11
I am also getting this issue with the iOS 10 beta.

**Comment by alexanderedge** [comment] 2016-08-09 08:27
This is fixed by https://github.com/RestKit/RestKit/pull/2449

**Closed** 2016-08-09 08:28 UTC

**Comment by kirankhalkar** [comment] 2017-02-20 11:41
Hello, I am using RestKit 0.27 , I'm facing above issue. I have 1200 entry few entry saved into database but after few entry I get above error. Let us know which way i can resolve this.

**Comment by Voidozzer** [comment] 2017-03-24 07:59
Same here. Using RestKit 0.27 and facing above issue.

**Comment by JanNash** [comment] 2017-03-24 10:30
Hey, I also ran into the problem. For me, pinning RestKit to a specific commit helped:
```
# Fetching a specific dev-version of RestKit due
# to an iOS10 introduced problem in RestKit
# For further information, see
# https://github.com/RestKit/RestKit/issues/2451
pod 'RestKit',
  :git => 'https://github.com/RestKit/RestKit.git',
  :commit => '9cbba9eb1b490c3c5e2873c8fba8e9c0fec1bf07'
```

**Comment by NinjaSudo** [comment] 2017-04-18 19:31
thx Jan, that helped, but when can we get this into a release?

**Comment by JanNash** [comment] 2017-04-19 08:22
Unfortunately, I can't answer that, since I'm not a member of the RestKit team or an active contributor. It's afaik a project they do in their spare time, so I guess there'll be a release when they find the time for it.

**Comment by jasconius** [comment] 2017-05-18 15:25
This issue is closed but this commit is still not in any official build. This seems like a pretty significant thing and is reproducible in iOS 10. When can we expect a 0.28?

**Comment by valeriomazzeo** [comment] 2017-05-18 15:57
@jasconius I tried to make a release https://github.com/RestKit/RestKit/pull/2466 but travis doesn't agree with me and unfortunately I have no time to fix it.

Anybody's help in making that PR green would be really appreciated.
