### ISSUE TITLE
RKObjectMapping.h Not Found

### ISSUE THREAD

**Issue by hieuld** [RestKit/RestKit#2302] opened 2015-09-14 10:49 UTC
I "pod update", and my RestKit version now is 0.25.0, my RKValueTransformers is 1.1.2, and an error appeared "RKObjectMapping.h" not found.

What did RestKit change in the new version, that I check on the its github cannot find anything.

Note: I am using XCode7-beta5, objective-c

**Comment by segiddins** [comment] 2015-09-14 14:39
This looks like a duplicate of #2288

**Closed by segiddins** 2015-09-14 14:39 UTC

**Comment by hieuld** [comment] 2015-09-14 14:43
So, how can I fix it? @segiddins ?

**Comment by segiddins** [comment] 2015-09-14 14:45
Make a pull request? I'm without a laptop now so I can check anything in Xcode.

**Comment by hieuld** [comment] 2015-09-14 14:47
I am quite new to github system. How can I make a pull request?

**Comment by hieuld** [comment] 2015-09-14 15:38
The thing is even I use the older version of RestKit (e.g., 0.23.1), the issue is still there.

**Comment by minaskamel** [comment] 2016-03-20 15:30
Downgrade Cococapods to 0.38.0 solved the issue for me.
