### ISSUE TITLE
RKPathMatcher crash: message sent to deallocated instance

### ISSUE THREAD

**Issue by la-himmel** [RestKit/RestKit#2133] opened 2015-01-15 09:21 UTC
Hello, 

I have a very frequent crash in the method 
(BOOL)matchesPath:sourceString tokenizeQueryStrings:parsedArguments: of the RKPathMatcher class, the first line: self.sourcePath = sourceString; and really not sure what to do with that. 

The message is "*** -[CFString release]: message sent to deallocated instance 0x....", sometimes it appears twice before crash.

Could you help please?

Thanks!

**Comment by segiddins** [comment] 2015-01-15 16:47
Can you please share a reproduction case?

**Comment by la-himmel** [comment] 2015-01-16 10:43
This is hard to do because my app is very complicated. On launch, many data is downloaded and mapped, and it occurs always at that time. I suppose this is caused by race condition (otherwise it should be more predictable). 
But maybe you already had some similar problems with this class before with known steps to reproduce it?

**Comment by la-himmel** [comment] 2015-01-16 14:36
I've caught the call that crashes.
RKObjectManager *objectManager = [RKObjectManager sharedManager];
RKObjectRequestOperation *operation = [objectManager appropriateObjectRequestOperationWithObject:nil
                                        method:RKRequestMethodGET    
                                             path:resultString 
                                  parameters:parameters];

**Comment by megakode** [comment] 2015-01-20 09:39
This is a duplicate of #1998.

**Comment by la-himmel** [comment] 2015-01-20 09:44
Thanks! I'll watch that thread.

**Comment by megakode** [comment] 2015-01-20 10:20
I have created a pull request with a fix for this #2141

**Closed** 2015-01-20 15:57 UTC
