### ISSUE TITLE
'lcl_RK.h' file not found in RKLog.h

### ISSUE THREAD

**Issue by Headmast** [RestKit/RestKit#2347] opened 2015-11-06 06:25 UTC
I install RestKit v0.25.0 with CocoaPods v0.39 in Xcode 7.1 and have problem with imports. When I used CocoaPods v0.38.2 everything was amazing.
"RKHTTPUtilities.h" file not found. It solves after set recursive in headers search path for "${PODS_ROOT}/Headers/Public/RestKit". But I get this error 'lcl_RK.h' file not found in RKLog.h.

I also try do [this](https://github.com/RestKit/RestKit/issues/2341#issue-114225520).

**Comment by Headmast** [comment] 2015-11-06 09:03
I found only one not the best way.  Add "$(PODS_ROOT)/RestKit/Vendor/LibComponentLogging/Core" in headers search path for project target.

Explain: lcl_RK.h file is in folder path RestKit/Vendor/LibComponentLogging/Core, all other files in folder RestKit/Code/. When CocoaPods generates Headers folder, it misses lcl_RK.h file.

**Comment by segiddins** [comment] 2015-11-06 14:41
This is a duplicate of several open issues, and it's something I've been working on addressing.

**Closed by segiddins** 2015-11-06 14:41 UTC
